// Crops database
export const cropsDatabase = {
  wheat: {
    name: "Wheat",
    season: "Winter",
    sowingMonth: "October",
    harvestMonth: "March",
    avgYield: "50 tons/hectare",
    waterNeeded: "450-650mm",
    soilType: "Loam, Clay loam",
    diseases: ["Rust", "Smut", "Powdery Mildew"],
    pesticides: ["Carbendazim", "Hexaconazole"],
  },
  rice: {
    name: "Rice",
    season: "Summer",
    sowingMonth: "May",
    harvestMonth: "September",
    avgYield: "60 tons/hectare",
    waterNeeded: "1000-1500mm",
    soilType: "Clay, Silt loam",
    diseases: ["Blast", "Brown Spot", "Sheath Blight"],
    pesticides: ["Triazophos", "Chlorpyrifos"],
  },
  cotton: {
    name: "Cotton",
    season: "Kharif",
    sowingMonth: "June",
    harvestMonth: "November",
    avgYield: "18 tons/hectare",
    waterNeeded: "500-600mm",
    soilType: "Black soil, Red soil",
    diseases: ["Leaf curl", "Wilt", "Bollworm"],
    pesticides: ["Profenofos", "Cypermethrin"],
  },
}
