// Dhalari (Trader) database
export const dhalariDatabase = [
  {
    id: "dhalari-1",
    name: "Sharma Trading",
    businessName: "Sharma Trading Company",
    email: "sharma@trading.com",
    phone: "+91 97654 32100",
    specialization: ["Wheat", "Rice"],
    location: "New Delhi",
    commission: 5,
    rating: 4.8,
    verified: true,
    experience: 20,
    createdAt: new Date(),
  },
  {
    id: "dhalari-2",
    name: "Patel Exports",
    businessName: "Patel Export Solutions",
    email: "patel@exports.com",
    phone: "+91 97654 32101",
    specialization: ["Cotton", "Groundnut"],
    location: "Gujarat",
    commission: 6,
    rating: 4.5,
    verified: true,
    experience: 15,
    createdAt: new Date(),
  },
  {
    id: "dhalari-3",
    name: "Green Markets",
    businessName: "Green Agricultural Markets",
    email: "green@markets.com",
    phone: "+91 97654 32102",
    specialization: ["Vegetables", "Fruits"],
    location: "Bangalore",
    commission: 4,
    rating: 4.9,
    verified: true,
    experience: 10,
    createdAt: new Date(),
  },
]
