// Farmer database with phone numbers and details
export const farmersDatabase = [
  {
    id: "farmer-1",
    name: "Raj Kumar",
    phone: "+91 98765 43210",
    email: "raj.kumar@example.com",
    location: "Punjab",
    crops: ["Wheat", "Rice"],
    landSize: 50,
    experience: 15,
    createdAt: new Date(),
  },
  {
    id: "farmer-2",
    name: "Priya Singh",
    phone: "+91 98765 43211",
    email: "priya.singh@example.com",
    location: "Haryana",
    crops: ["Rice", "Corn"],
    landSize: 30,
    experience: 8,
    createdAt: new Date(),
  },
  {
    id: "farmer-3",
    name: "Amit Patel",
    phone: "+91 98765 43212",
    email: "amit.patel@example.com",
    location: "Gujarat",
    crops: ["Cotton", "Groundnut"],
    landSize: 20,
    experience: 12,
    createdAt: new Date(),
  },
]
