// Farmer requests database
export const requestsDatabase = [
  {
    id: "req-1",
    farmerId: "farmer-1",
    farmerName: "Raj Kumar",
    farmerPhone: "+91 98765 43210",
    crop: "Wheat",
    quantity: "50 tons",
    expectedPrice: "₹2,500/qt",
    description: "High quality wheat, ready for harvest",
    location: "Punjab",
    status: "pending",
    urgency: "high",
    createdAt: new Date(),
  },
  {
    id: "req-2",
    farmerId: "farmer-2",
    farmerName: "Priya Singh",
    farmerPhone: "+91 98765 43211",
    crop: "Rice",
    quantity: "30 tons",
    expectedPrice: "₹3,200/qt",
    description: "Premium Basmati rice",
    location: "Haryana",
    status: "pending",
    urgency: "medium",
    createdAt: new Date(),
  },
  {
    id: "req-3",
    farmerId: "farmer-3",
    farmerName: "Amit Patel",
    farmerPhone: "+91 98765 43212",
    crop: "Cotton",
    quantity: "20 tons",
    expectedPrice: "₹5,500/qt",
    description: "Grade A cotton",
    location: "Gujarat",
    status: "accepted",
    urgency: "low",
    createdAt: new Date(),
  },
]
