"use client"

import { createContext, useContext, useState, type ReactNode, useEffect } from "react"

type Language = "en" | "te" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "common.logout": "Logout",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.back": "Back to Dashboard",
    "common.loading": "Loading...",
    "common.available": "Available",
    "common.sold": "Sold",
    "common.message": "Message",
    "common.accept": "Accept",
    "common.decline": "Decline",
    "common.success": "Success",
    "common.error": "Error",
    "common.myProfile": "My Profile", // Added myProfile translation
    notifications: "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.noNotifications": "No notifications yet",
    "notifications.unread": "unread notification",
    "notifications.unreadPlural": "unread notifications",
    // Farmer Dashboard
    "farmer.welcome": "Welcome, Farmer!",
    "farmer.subtitle": "Manage your crops, track prices, and connect with traders",
    "farmer.activeCrops": "Active Crops",
    "farmer.traderRequests": "Trader Requests",
    "farmer.avgPrice": "Average Price",
    "farmer.perQuintal": "Per quintal",
    "farmer.successRate": "Success Rate",
    "farmer.transactions": "Transactions",
    "farmer.yieldPerformance": "Crop Performance",
    "farmer.yourYieldVsAverage": "Your crops vs. region average",
    "farmer.quickActions": "Quick Actions",
    "farmer.predictCrop": "Predict Crop",
    "farmer.pricePredictions": "Price Predictions",
    "farmer.findTraders": "Find Traders",
    "farmer.addMyCrop": "Add My Crop",
    "farmer.needHelp": "Need Help?",
    "farmer.support": "Support",
    "farmer.myCrops": "My Active Crops",
    "farmer.myCropsDescription": "View and manage all your listed crops",
    "farmer.noCrops": "You haven't added any crops yet",
    "farmer.traderRequestsDescription": "Manage requests from traders interested in your crops",
    "farmer.noTraderRequests": "No trader requests at the moment",
    // Farmer Add Crop
    "addCrop.title": "Add Your Crop for Sale",
    "addCrop.subtitle": "List your crop details to connect with traders",
    "addCrop.cropName": "Crop Name",
    "addCrop.cropNamePlaceholder": "e.g., Wheat, Rice, Cotton",
    "addCrop.quantity": "Quantity (in Kg)",
    "addCrop.quantityPlaceholder": "e.g., 5000",
    "addCrop.pricePerKg": "Price Per Kg (₹)",
    "addCrop.pricePlaceholder": "e.g., 25",
    "addCrop.location": "Location",
    "addCrop.locationPlaceholder": "e.g., Punjab",
    "addCrop.description": "Description",
    "addCrop.descriptionPlaceholder": "Quality, harvest date, etc.",
    "addCrop.phone": "Contact Phone",
    "addCrop.phonePlaceholder": "+91 98765 43210",
    "addCrop.success": "Crop listed successfully!",
    // Dhalari Dashboard
    "dhalari.welcome": "Welcome, Trader!",
    "dhalari.subtitle": "Manage farmer requests, track earnings, and grow your business",
    "dhalari.pendingRequests": "Pending Requests",
    "dhalari.acceptedDeals": "Accepted Deals",
    "dhalari.totalEarnings": "Total Amount Spent",
    "dhalari.thisMonth": "This month",
    "dhalari.avgDealValue": "Average Deal Value",
    "dhalari.perTransaction": "Per status",
    "dhalari.weeklyEarnings": "Weekly Spending",
    "dhalari.yourEarningsThisWeek": "Your spending this week",
    "dhalari.viewRequests": "View Requests",
    "dhalari.myProfile": "My Profile",
    "dhalari.analytics": "Analytics",
    "dhalari.profileStats": "Profile Stats",
    "dhalari.rating": "Rating",
    "dhalari.successRate": "Success Rate",
    "dhalari.verified": "Verified",
    // Dhalari Requests
    "requests.title": "Farmer Crop Listings",
    "requests.subtitle": "Browse available crops from farmers",
    "requests.farmerName": "Farmer Name",
    "requests.crop": "Crop",
    "requests.quantity": "Quantity",
    "requests.price": "Price",
    "requests.location": "Location",
    "requests.phone": "Phone",
    "requests.accept": "Accept Deal",
    "requests.contact": "Contact Farmer",
    // Find Verified Traders
    find_verified_traders: "Find Verified Traders",
    connect_with_trusted_dhalaris: "Connect with trusted dhalaris (agricultural traders) in your area",
    filter_by_crop: "Filter by Crop",
    filter_by_location: "Filter by Location",
    all_crops: "All Crops",
    wheat: "Wheat",
    rice: "Rice",
    cotton: "Cotton",
    sugarcane: "Sugarcane",
    all_locations: "All Locations",
    punjab: "Punjab",
    haryana: "Haryana",
    maharashtra: "Maharashtra",
    delhi: "Delhi",
    west_bengal: "West Bengal",
    specializations: "Specializations",
    experience: "Experience",
    years: "years",
    commission_rate: "Commission Rate",
    contacting: "Contacting",
    no_traders_found: "No traders found with selected filters. Try adjusting your search.",
    // Dashboard Stats
    "dashboard.availableCrops": "Available Crops",
    "dashboard.clickBrowse": "Click to browse marketplace",
    "dashboard.view": "View",
    "dashboard.activePartnerships": "Active partnerships",
    "dashboard.commissionEarned": "On accepted crops",
    "dashboard.currentlyListed": "Currently listed",
    "dashboard.cropRequests": "Crop Requests",
    "dashboard.fromDealers": "From dealers for your crops",
    "dashboard.contactRequests": "Contact Requests",
    "dashboard.connectionRequests": "Connection requests",
    "dashboard.signIn": "Sign In",
    "dashboard.goHome": "Go to Home",
    "dashboard.signInGoogle": "Sign in with Google",
    "dashboard.pleaseSignIn": "Please sign in to access your dashboard",
    "dashboard.farmerDashboard": "Farmer Dashboard",
    "dashboard.dhalariDashboard": "Dhalari Dashboard",
    // Performance Statistics
    "stats.performanceStatistics": "📊 Performance Statistics",
    "stats.dealSuccessRate": "Deal Success Rate",
    "stats.excellent": "Excellent",
    "stats.good": "Good",
    "stats.needsImprovement": "Needs Improvement",
    "stats.starting": "Starting",
    "stats.acceptedOutOf": "accepted out of",
    "stats.totalRequests": "total requests",
    "stats.basedOnDeals": "Based on accepted deals",
    "stats.revenueBreakdown": "Revenue Breakdown",
    "stats.totalTradeValue": "Total Trade Value",
    "stats.yourCommission": "Your Commission (10%)",
    "stats.avgPerDeal": "Avg. per Deal",
    "stats.todaysMarket": "Today's Market Status",
    "stats.marketTrend": "Market Trend",
    "stats.activeFarmers": "Active Farmers",
    "stats.newListingsToday": "New Listings Today",
    "stats.topCrop": "Top Crop",
    "stats.totalListings": "Total Listings",
    "stats.monthlyPerformance": "📈 Monthly Performance Summary",
    "stats.tradingPerformance": "Your trading performance over recent months",
    "stats.deals": "deals",
    "stats.requestSummary": "Request Summary",
    "stats.cropDeals": "Crop Deals",
    "stats.total": "Total",
    "stats.yourStatus": "Your Status",
    "stats.activeCrops": "Active Crops",
    "stats.avgPriceQuintal": "Avg Price/Quintal",
    "stats.profileStatus": "Profile Status",
    "stats.active": "Active",
    "stats.monthlyPerformanceChart": "Monthly Performance",
    "stats.chartDescription": "Crops, Requests, Sales & Revenue",
    // Quick Actions
    "actions.manageTrading": "Manage your trading activities",
    "actions.manageActivities": "Manage your activities",
    "actions.contactRequests": "Contact Requests",
    "actions.browseMarketplace": "Browse Marketplace",
    "actions.connectionsChat": "💬 Connections & Chat",
    "actions.findFarmers": "Find Farmers",
    // Support
    "support.querySupport": "Query Support & Help",
    "support.needAssistance": "Need assistance? Get help with platform features and resolve your queries",
    "support.commonTopics": "Common Topics:",
    "support.paymentDisputes": "Payment disputes & transaction issues",
    "support.profileVerification": "Profile verification help",
    "support.marketplaceGuidelines": "Marketplace listing guidelines",
    "support.openSupportCenter": "Open Support Center",
    "support.queryAndSupport": "Query & Support",
    "support.getHelp": "Get help with your questions or report issues",
    "support.submitQuery": "Submit a Query",
    "support.fillForm": "Fill out the form below and we'll get back to you soon",
    "support.queryCategory": "Query Category *",
    "support.selectCategory": "Select category",
    "support.technicalIssue": "Technical Issue",
    "support.paymentRelated": "Payment Related",
    "support.cropInformation": "Crop Information",
    "support.farmerContact": "Farmer Contact",
    "support.other": "Other",
    "support.subject": "Subject *",
    "support.subjectPlaceholder": "Brief description of your issue",
    "support.description": "Description *",
    "support.descriptionPlaceholder": "Describe your query in detail...",
    "support.submitting": "Submitting...",
    "support.submitQueryBtn": "Submit Query",
    "support.contactSupport": "Contact Support",
    "support.phoneSupport": "Phone Support",
    "support.emailSupport": "Email Support",
    "support.platformInstructions": "Platform Instructions",
    "support.quickGuide": "Quick guide to using AgriConnect as a trader",
    "support.browseAvailCrops": "1. Browse Available Crops",
    "support.browseAvailCropsDesc": "Go to \"View Requests\" to see all crop listings from farmers with details like quantity, price, and location.",
    "support.acceptDeals": "2. Accept Deals",
    "support.acceptDealsDesc": "Click \"Accept\" on any listing to finalize the deal. You'll earn 5% commission on the total value.",
    "support.sendCropRequests": "3. Send Crop Requests",
    "support.sendCropRequestsDesc": "Use \"Send Crop Request\" to tell farmers what crops you're looking for. Farmers will be notified.",
    "support.trackEarnings": "4. Track Earnings",
    "support.trackEarningsDesc": "View your analytics and earnings breakdown in the dashboard and analytics sections.",
    "support.faq": "Frequently Asked Questions",
    "support.faq1q": "How do I contact farmers?",
    "support.faq1a": "Each crop listing shows the farmer's phone number. You can call or WhatsApp them directly to discuss the deal details.",
    "support.faq2q": "What is the commission rate?",
    "support.faq2a": "You earn 5% commission on every deal you accept. For example, on a ₹100,000 deal, you earn ₹5,000.",
    "support.faq3q": "How do I get paid?",
    "support.faq3a": "Earnings are tracked automatically. Set up your bank details in your profile to receive direct transfers at the end of each month.",
    "support.faq4q": "Can I decline a deal after accepting?",
    "support.faq4a": "Once accepted, deals are finalized. Please contact support immediately if you need to cancel due to exceptional circumstances.",
    "support.faq5q": "How do I update my profile?",
    "support.faq5a": "Go to \"My Profile\" in the quick actions section to edit your business information, crop specializations, and contact details.",
    "support.querySubmitted": "Your query has been submitted. We'll respond within 24 hours.",
    "support.fillAllFields": "Please fill all fields",
    "support.failedSubmit": "Failed to submit query",
    // Marketplace
    "market.cropMarketplace": "Crop Marketplace",
    "market.browseDescription": "Browse available crops from farmers and make offers directly.",
    "market.searchPlaceholder": "Search crops, farmers, or location...",
    "market.loadingData": "Loading market data...",
    "market.noCrops": "No crops currently available in the market.",
    "market.requestDeal": "Request Deal",
    "market.makeOffer": "Make an Offer for",
    "market.sendPurchase": "Send a purchase request to",
    "market.quantity": "Quantity (kg)",
    "market.available": "Available:",
    "market.offerPrice": "Offer Price (₹/kg)",
    "market.expected": "Expected:",
    "market.messageOptional": "Message (Optional)",
    "market.messagePlaceholder": "Add delivery details or negotiation notes...",
    "market.sending": "Sending...",
    "market.sendRequest": "Send Request",
    "market.requestSent": "Request Sent!",
    "market.locationNotSpecified": "Location not specified",
    "market.hiddenConnect": "Hidden (Connect)",
    "market.connected": "Connected",
    "market.back": "Back",
    // Connections & Chat
    "chat.connectionsAndChat": "Connections & Chat",
    "chat.connected": "Connected",
    "chat.connections": "Connections",
    "chat.requests": "Requests",
    "chat.searchConnections": "Search connections...",
    "chat.noConnections": "No connections yet",
    "chat.findTradersHint": "Find traders and send requests to connect",
    "chat.findFarmersHint": "Find farmers and send requests to connect",
    "chat.startChatting": "Connected — Start chatting!",
    "chat.noPendingRequests": "No pending requests",
    "chat.yourMessages": "Your Messages",
    "chat.selectConnection": "Select a connection to start chatting",
    "chat.connectedOn": "Connected on",
    "chat.sayHello": "👋 Say hello! Start the conversation.",
    "chat.typeMessage": "Type a message...",
    "chat.accessDenied": "Access Denied",
    "chat.signInFarmer": "Please sign in as a farmer.",
    "chat.signInDealer": "Please sign in as a dealer.",
  },
  te: {
    // Common
    "common.logout": "లాగోవుట్",
    "common.submit": "సమర్పించు",
    "common.cancel": "రద్దు",
    "common.save": "సేవ్ చేయి",
    "common.back": "డాష్‌బోర్డ్‌కు తిరిగి",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.available": "అందుబాటులో ఉంది",
    "common.sold": "విక్రయించబడింది",
    "common.message": "సందేశం",
    "common.accept": "అంగీకరించు",
    "common.decline": "తిరస్కరించు",
    "common.success": "విజయం",
    "common.error": "లోపం",
    "common.myProfile": "నా ప్రొఫైల్", // Added myProfile translation in Telugu
    notifications: "నోటిఫికేషన్లు",
    "notifications.markAllRead": "అన్నింటినీ చదివినట్లు గుర్తించు",
    "notifications.noNotifications": "ఇంకా నోటిఫికేషన్లు లేవు",
    "notifications.unread": "చదవని నోటిఫికేషన్",
    "notifications.unreadPlural": "చదవని నోటిఫికేషన్లు",
    // Farmer Dashboard
    "farmer.welcome": "స్వాగతం, రైతు!",
    "farmer.subtitle": "మీ పంటలను నిర్వహించండి, ధరలను ట్రాక్ చేయండి మరియు వర్తకులతో సంయోగం చేయండి",
    "farmer.activeCrops": "సక్రియ పంటలు",
    "farmer.traderRequests": "వర్తక అభ్యర్థనలు",
    "farmer.avgPrice": "సగటు ధర",
    "farmer.perQuintal": "క్విన్టాల్‌కు",
    "farmer.successRate": "విజయ రేటు",
    "farmer.transactions": "లావాదేవీలు",
    "farmer.yieldPerformance": "పంట పనితీరు",
    "farmer.yourYieldVsAverage": "మీ పంటలు vs. ప్రాంత సగటు",
    "farmer.quickActions": "త్వరిత చర్యలు",
    "farmer.predictCrop": "పంట అంచనా",
    "farmer.pricePredictions": "ధర అంచనాలు",
    "farmer.findTraders": "వర్తకులను కనుగొనండి",
    "farmer.addMyCrop": "నా పంట జోడించు",
    "farmer.needHelp": "సహాయం కావాలా?",
    "farmer.support": "సపోర్టు",
    "farmer.myCrops": "నా సక్రియ పంటలు",
    "farmer.myCropsDescription": "మీ జాబితా చేసిన పంటలన్నింటినీ చూడండి మరియు నిర్వహించండి",
    "farmer.noCrops": "మీరు ఇంకా ఎటువంటి పంటలను జోడించలేదు",
    "farmer.traderRequestsDescription": "మీ పంటలపై ఆసక్తి కలిగి ఉన్న వర్తకుల నుండి అభ్యర్థనలను నిర్వహించండి",
    "farmer.noTraderRequests": "ప్రస్తుతం వర్తక అభ్యర్థనలు లేవు",
    // Farmer Add Crop
    "addCrop.title": "విక్రయం కోసం మీ పంట జోడించండి",
    "addCrop.subtitle": "వర్తకులతో కనెక్ట్ అవ్వడానికి మీ పంట వివరాలను జాబితా చేయండి",
    "addCrop.cropName": "పంట పేరు",
    "addCrop.cropNamePlaceholder": "ఉదా., గోధుమ, బియ్యం, పత్తి",
    "addCrop.quantity": "పరిమాణం (కిలోలలో)",
    "addCrop.quantityPlaceholder": "ఉదా., 5000",
    "addCrop.pricePerKg": "కిలోకు ధర (₹)",
    "addCrop.pricePlaceholder": "ఉదా., 25",
    "addCrop.location": "స్థానం",
    "addCrop.locationPlaceholder": "ఉదా., పంజాబ్",
    "addCrop.description": "వివరణ",
    "addCrop.descriptionPlaceholder": "నాణ్యత, పంట తేదీ, మొదలైనవి",
    "addCrop.phone": "సంప్రదింపు ఫోన్",
    "addCrop.phonePlaceholder": "+91 98765 43210",
    "addCrop.success": "పంట విజయవంతంగా జాబితా చేయబడింది!",
    // Dhalari Dashboard
    "dhalari.welcome": "స్వాగతం, వర్తకుడు!",
    "dhalari.subtitle": "రైత అభ్యర్థనలను నిర్వహించండి, ఆదాయాన్ని ట్రాక్ చేయండి మరియు మీ వ్యాపారాన్ని పెంచండి",
    "dhalari.pendingRequests": "అందుబాటులో ఉన్న పంటలు",
    "dhalari.acceptedDeals": "ఆమోదించిన ఒప్పందాలు",
    "dhalari.totalEarnings": "మొత్తం ఖర్చు",
    "dhalari.thisMonth": "ఈ నెలలో",
    "dhalari.avgDealValue": "సగటు ఒప్పందం విలువ",
    "dhalari.perTransaction": "స్థితి ప్రకారం",
    "dhalari.weeklyEarnings": "వారపు ఖర్చు",
    "dhalari.yourEarningsThisWeek": "ఈ వారం మీ ఖర్చు",
    "dhalari.viewRequests": "పంటలను చూడండి",
    "dhalari.myProfile": "నా ప్రొఫైల్",
    "dhalari.analytics": "విశ్లేషణలు",
    "dhalari.profileStats": "ప్రొఫైల్ గణాంకాలు",
    "dhalari.rating": "రేటింగ్",
    "dhalari.successRate": "విజయ రేటు",
    "dhalari.verified": "ధృవీకరించబడిన",
    // Dhalari Requests
    "requests.title": "రైతు పంట జాబితాలు",
    "requests.subtitle": "రైతుల నుండి అందుబాటులో ఉన్న పంటలను బ్రౌజ్ చేయండి",
    "requests.farmerName": "రైతు పేరు",
    "requests.crop": "పంట",
    "requests.quantity": "పరిమాణం",
    "requests.price": "ధర",
    "requests.location": "స్థానం",
    "requests.phone": "ఫోన్",
    "requests.accept": "ఒప్పందాన్ని అంగీకరించు",
    "requests.contact": "రైతును సంప్రదించండి",
    // Find Verified Traders
    find_verified_traders: "ధృవీకరించబడిన వర్తకులను కనుగొనండి",
    connect_with_trusted_dhalaris: "మీ ప్రాంతంలో విశ్వసనీయ దళారీలు (వ్యవసాయ వర్తకులు)తో కనెక్ట్ అవ్వండి",
    filter_by_crop: "పంట ద్వారా ఫిల్టర్ చేయండి",
    filter_by_location: "స్థానం ద్వారా ఫిల్టర్ చేయండి",
    all_crops: "అన్ని పంటలు",
    wheat: "గోధుమలు",
    rice: "బియ్యం",
    cotton: "పత్తి",
    sugarcane: "చెరకు",
    all_locations: "అన్ని స్థానాలు",
    punjab: "పంజాబ్",
    haryana: "హర్యానా",
    maharashtra: "మహారాష్ట్ర",
    delhi: "ఢిల్లీ",
    west_bengal: "పశ్చిమ బెంగాల్",
    specializations: "ప్రత్యేకతలు",
    experience: "అనుభవం",
    years: "సంవత్సరాలు",
    commission_rate: "కమీషన్ రేటు",
    contacting: "సంప్రదిస్తోంది",
    no_traders_found: "ఎంచుకున్న ఫిల్టర్లతో వర్తకులు కనుగొనబడలేదు. మీ శోధనను సర్దుబాటు చేయడానికి ప్రయత్నించండి.",
    "dashboard.availableCrops": "అందుబాటులో ఉన్న పంటలు",
    "dashboard.clickBrowse": "మార్కెట్‌ప్లేస్ బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
    "dashboard.view": "చూడండి",
    "dashboard.activePartnerships": "యాక్టివ్ భాగస్వామ్యాలు",
    "dashboard.commissionEarned": "ఆమోదించిన పంటలపై",
    "dashboard.currentlyListed": "ప్రస్తుతం జాబితా చేయబడింది",
    "dashboard.cropRequests": "పంట అభ్యర్థనలు",
    "dashboard.fromDealers": "మీ పంటల కోసం డీలర్ల నుండి",
    "dashboard.contactRequests": "సంప్రదింపు అభ్యర్థనలు",
    "dashboard.connectionRequests": "కనెక్షన్ అభ్యర్థనలు",
    "dashboard.signIn": "సైన్ ఇన్",
    "dashboard.goHome": "హోమ్‌కి వెళ్ళండి",
    "dashboard.signInGoogle": "Google తో సైన్ ఇన్ చేయండి",
    "dashboard.pleaseSignIn": "మీ డ్యాష్‌బోర్డ్‌ని యాక్సెస్ చేయడానికి దయచేసి సైన్ ఇన్ చేయండి",
    "dashboard.farmerDashboard": "రైతు డ్యాష్‌బోర్డ్",
    "dashboard.dhalariDashboard": "ధాలరీ డ్యాష్‌బోర్డ్",
    "stats.performanceStatistics": "📊 పనితీరు గణాంకాలు",
    "stats.dealSuccessRate": "డీల్ విజయ రేటు",
    "stats.excellent": "అద్భుతం",
    "stats.good": "మంచిది",
    "stats.needsImprovement": "మెరుగుపడాలి",
    "stats.starting": "ప్రారంభం",
    "stats.acceptedOutOf": "ఆమోదించబడినవి",
    "stats.totalRequests": "మొత్తం అభ్యర్థనలు",
    "stats.basedOnDeals": "ఆమోదించిన డీల్స్ ఆధారంగా",
    "stats.revenueBreakdown": "ఆదాయ విభజన",
    "stats.totalTradeValue": "మొత్తం వ్యాపార విలువ",
    "stats.yourCommission": "మీ కమీషన్ (10%)",
    "stats.avgPerDeal": "డీల్‌కు సగటు",
    "stats.todaysMarket": "ఈరోజు మార్కెట్ స్థితి",
    "stats.marketTrend": "మార్కెట్ ట్రెండ్",
    "stats.activeFarmers": "యాక్టివ్ రైతులు",
    "stats.newListingsToday": "ఈరోజు కొత్త జాబితాలు",
    "stats.topCrop": "టాప్ పంట",
    "stats.totalListings": "మొత్తం జాబితాలు",
    "stats.monthlyPerformance": "📈 నెలవారీ పనితీరు సారాంశం",
    "stats.tradingPerformance": "ఇటీవలి నెలల్లో మీ వ్యాపార పనితీరు",
    "stats.deals": "డీల్స్",
    "stats.requestSummary": "అభ్యర్థన సారాంశం",
    "stats.cropDeals": "పంట డీల్స్",
    "stats.total": "మొత్తం",
    "stats.yourStatus": "మీ స్థితి",
    "stats.activeCrops": "యాక్టివ్ పంటలు",
    "stats.avgPriceQuintal": "క్వింటాల్‌కు సగటు ధర",
    "stats.profileStatus": "ప్రొఫైల్ స్థితి",
    "stats.active": "యాక్టివ్",
    "stats.monthlyPerformanceChart": "నెలవారీ పనితీరు",
    "stats.chartDescription": "పంటలు, అభ్యర్థనలు, అమ్మకాలు & ఆదాయం",
    "actions.manageTrading": "మీ వ్యాపార కార్యకలాపాలను నిర్వహించండి",
    "actions.manageActivities": "మీ కార్యకలాపాలను నిర్వహించండి",
    "actions.contactRequests": "సంప్రదింపు అభ్యర్థనలు",
    "actions.browseMarketplace": "మార్కెట్‌ప్లేస్ బ్రౌజ్ చేయండి",
    "actions.connectionsChat": "💬 కనెక్షన్లు & చాట్",
    "actions.findFarmers": "రైతులను కనుగొనండి",
    "support.querySupport": "ప్రశ్న సహాయం & సహాయం",
    "support.needAssistance": "సహాయం కావాలా? ప్లాట్‌ఫారమ్ ఫీచర్లతో సహాయం పొందండి మరియు మీ ప్రశ్నలను పరిష్కరించుకోండి",
    "support.commonTopics": "సాధారణ అంశాలు:",
    "support.paymentDisputes": "చెల్లింపు వివాదాలు & లావాదేవీ సమస్యలు",
    "support.profileVerification": "ప్రొఫైల్ ధృవీకరణ సహాయం",
    "support.marketplaceGuidelines": "మార్కెట్‌ప్లేస్ జాబితా మార్గదర్శకాలు",
    "support.openSupportCenter": "సపోర్ట్ సెంటర్ తెరవండి",
    "support.queryAndSupport": "ప్రశ్న & సహాయం",
    "support.getHelp": "మీ ప్రశ్నలకు సహాయం పొందండి లేదా సమస్యలను నివేదించండి",
    "support.submitQuery": "ప్రశ్న సమర్పించండి",
    "support.fillForm": "దిగువ ఫారమ్‌ను నింపండి మరియు మేము త్వరలో మీకు తిరిగి వస్తాము",
    "support.queryCategory": "ప్రశ్న వర్గం *",
    "support.selectCategory": "వర్గం ఎంచుకోండి",
    "support.technicalIssue": "సాంకేతిక సమస్య",
    "support.paymentRelated": "చెల్లింపు సంబంధిత",
    "support.cropInformation": "పంట సమాచారం",
    "support.farmerContact": "రైతు సంప్రదింపు",
    "support.other": "ఇతర",
    "support.subject": "విషయం *",
    "support.subjectPlaceholder": "మీ సమస్య యొక్క సంక్షిప్త వివరణ",
    "support.description": "వివరణ *",
    "support.descriptionPlaceholder": "మీ ప్రశ్నను వివరంగా వివరించండి...",
    "support.submitting": "సమర్పిస్తోంది...",
    "support.submitQueryBtn": "ప్రశ్న సమర్పించు",
    "support.contactSupport": "సపోర్ట్‌ను సంప్రదించండి",
    "support.phoneSupport": "ఫోన్ సపోర్ట్",
    "support.emailSupport": "ఇమెయిల్ సపోర్ట్",
    "support.platformInstructions": "ప్లాట్‌ఫారమ్ సూచనలు",
    "support.quickGuide": "వ్యాపారిగా AgriConnect ఉపయోగించడానికి త్వరిత గైడ్",
    "support.browseAvailCrops": "1. అందుబాటులో ఉన్న పంటలను బ్రౌజ్ చేయండి",
    "support.browseAvailCropsDesc": "రైతుల నుండి పంట జాబితాలను పరిమాణం, ధర మరియు స్థానం వంటి వివరాలతో చూడటానికి \"అభ్యర్థనలు చూడండి\"కి వెళ్ళండి.",
    "support.acceptDeals": "2. డీల్స్ అంగీకరించండి",
    "support.acceptDealsDesc": "డీల్‌ను ఖరారు చేయడానికి ఏదైనా జాబితాపై \"అంగీకరించు\" క్లిక్ చేయండి. మీరు మొత్తం విలువలో 5% కమీషన్ సంపాదిస్తారు.",
    "support.sendCropRequests": "3. పంట అభ్యర్థనలు పంపండి",
    "support.sendCropRequestsDesc": "మీరు ఏ పంటలను వెతుకుతున్నారో రైతులకు చెప్పడానికి \"పంట అభ్యర్థన పంపు\" ఉపయోగించండి. రైతులకు నోటిఫికేషన్ వస్తుంది.",
    "support.trackEarnings": "4. ఆదాయాన్ని ట్రాక్ చేయండి",
    "support.trackEarningsDesc": "డ్యాష్‌బోర్డ్ మరియు ఎనలిటిక్స్ సెక్షన్‌లలో మీ ఎనలిటిక్స్ మరియు ఆదాయ విభజనను చూడండి.",
    "support.faq": "తరచుగా అడిగే ప్రశ్నలు",
    "support.faq1q": "రైతులను ఎలా సంప్రదించాలి?",
    "support.faq1a": "ప్రతి పంట జాబితాలో రైతు ఫోన్ నంబర్ చూపిస్తుంది. డీల్ వివరాలను చర్చించడానికి మీరు వారికి నేరుగా కాల్ చేయవచ్చు లేదా WhatsApp చేయవచ్చు.",
    "support.faq2q": "కమీషన్ రేటు ఎంత?",
    "support.faq2a": "మీరు అంగీకరించే ప్రతి డీల్‌పై 5% కమీషన్ సంపాదిస్తారు. ఉదాహరణకు, ₹1,00,000 డీల్‌పై, మీరు ₹5,000 సంపాదిస్తారు.",
    "support.faq3q": "నాకు ఎలా చెల్లించబడుతుంది?",
    "support.faq3a": "ఆదాయాలు స్వయంచాలకంగా ట్రాక్ చేయబడతాయి. ప్రతి నెల చివరలో డైరెక్ట్ ట్రాన్స్‌ఫర్లు పొందడానికి మీ ప్రొఫైల్‌లో బ్యాంక్ వివరాలు సెటప్ చేయండి.",
    "support.faq4q": "అంగీకరించిన తర్వాత డీల్‌ను తిరస్కరించవచ్చా?",
    "support.faq4a": "అంగీకరించిన తర్వాత, డీల్స్ ఖరారు అవుతాయి. అసాధారణ పరిస్థితుల కారణంగా మీరు రద్దు చేయాల్సి వస్తే దయచేసి సపోర్ట్‌ను వెంటనే సంప్రదించండి.",
    "support.faq5q": "నా ప్రొఫైల్‌ను ఎలా అప్‌డేట్ చేయాలి?",
    "support.faq5a": "మీ వ్యాపార సమాచారం, పంట స్పెషలైజేషన్లు మరియు సంప్రదింపు వివరాలను ఎడిట్ చేయడానికి క్విక్ యాక్షన్స్ సెక్షన్‌లో \"నా ప్రొఫైల్\"కి వెళ్ళండి.",
    "support.querySubmitted": "మీ ప్రశ్న సమర్పించబడింది. 24 గంటల్లో మేము ప్రతిస్పందిస్తాము.",
    "support.fillAllFields": "దయచేసి అన్ని ఫీల్డ్‌లను నింపండి",
    "support.failedSubmit": "ప్రశ్న సమర్పించడంలో విఫలమైంది",
    "market.cropMarketplace": "పంట మార్కెట్‌ప్లేస్",
    "market.browseDescription": "రైతుల నుండి అందుబాటులో ఉన్న పంటలను బ్రౌజ్ చేయండి మరియు నేరుగా ఆఫర్లు చేయండి.",
    "market.searchPlaceholder": "పంటలు, రైతులు లేదా ప్రాంతం శోధించండి...",
    "market.loadingData": "మార్కెట్ డేటా లోడ్ అవుతోంది...",
    "market.noCrops": "మార్కెట్‌లో ప్రస్తుతం పంటలు అందుబాటులో లేవు.",
    "market.requestDeal": "డీల్ అభ్యర్థించు",
    "market.makeOffer": "ఆఫర్ ఇవ్వండి",
    "market.sendPurchase": "కొనుగోలు అభ్యర్థన పంపండి",
    "market.quantity": "పరిమాణం (కేజీ)",
    "market.available": "అందుబాటు:",
    "market.offerPrice": "ఆఫర్ ధర (₹/కేజీ)",
    "market.expected": "అంచనా:",
    "market.messageOptional": "సందేశం (ఐచ్ఛికం)",
    "market.messagePlaceholder": "డెలివరీ వివరాలు లేదా చర్చా గమనికలు జోడించండి...",
    "market.sending": "పంపుతోంది...",
    "market.sendRequest": "అభ్యర్థన పంపు",
    "market.requestSent": "అభ్యర్థన పంపబడింది!",
    "market.locationNotSpecified": "ప్రాంతం పేర్కొనబడలేదు",
    "market.hiddenConnect": "దాచబడింది (కనెక్ట్)",
    "market.connected": "కనెక్ట్ అయ్యారు",
    "market.back": "వెనుకకు",
    "chat.connectionsAndChat": "కనెక్షన్లు & చాట్",
    "chat.connected": "కనెక్ట్ అయ్యారు",
    "chat.connections": "కనెక్షన్లు",
    "chat.requests": "అభ్యర్థనలు",
    "chat.searchConnections": "కనెక్షన్లలో వెతకండి...",
    "chat.noConnections": "ఇంకా కనెక్షన్లు లేవు",
    "chat.findTradersHint": "వర్తకులను కనుగొని కనెక్ట్ అవ్వడానికి అభ్యర్థనలు పంపండి",
    "chat.findFarmersHint": "రైతులను కనుగొని కనెక్ట్ అవ్వడానికి అభ్యర్థనలు పంపండి",
    "chat.startChatting": "కనెక్ట్ అయ్యారు — చాట్ చేయండి!",
    "chat.noPendingRequests": "పెండింగ్ అభ్యర్థనలు లేవు",
    "chat.yourMessages": "మీ సందేశాలు",
    "chat.selectConnection": "చాట్ ప్రారంభించడానికి ఒక కనెక్షన్ ఎంచుకోండి",
    "chat.connectedOn": "కనెక్ట్ అయిన తేదీ",
    "chat.sayHello": "👋 హలో చెప్పండి! సంభాషణ ప్రారంభించండి.",
    "chat.typeMessage": "సందేశం టైప్ చేయండి...",
    "chat.accessDenied": "ప్రాప్యత నిరాకరించబడింది",
    "chat.signInFarmer": "దయచేసి రైతుగా సైన్ ఇన్ చేయండి.",
    "chat.signInDealer": "దయచేసి డీలర్‌గా సైన్ ఇన్ చేయండి.",
  },
  hi: {
    // Common
    "common.logout": "लॉगआउट",
    "common.submit": "जमा करें",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.back": "डैशबोर्ड पर वापस",
    "common.loading": "लोड हो रहा है...",
    "common.available": "उपलब्ध",
    "common.sold": "बिक गया",
    "common.message": "संदेश",
    "common.accept": "स्वीकार करें",
    "common.decline": "अस्वीकार करें",
    "common.success": "सफलता",
    "common.error": "त्रुटि",
    "common.myProfile": "मेरी प्रोफ़ाइल", // Added myProfile translation in Hindi
    notifications: "सूचनाएं",
    "notifications.markAllRead": "सभी को पढ़ा हुआ चिह्नित करें",
    "notifications.noNotifications": "अभी तक कोई सूचना नहीं",
    "notifications.unread": "अपठित सूचना",
    "notifications.unreadPlural": "अपठित सूचनाएं",
    // Farmer Dashboard
    "farmer.welcome": "स्वागत है, किसान!",
    "farmer.subtitle": "अपनी फसलों को प्रबंधित करें, कीमतों को ट्रैक करें और व्यापारियों से जुड़ें",
    "farmer.activeCrops": "सक्रिय फसलें",
    "farmer.traderRequests": "व्यापारी अनुरोध",
    "farmer.avgPrice": "औसत मूल्य",
    "farmer.perQuintal": "प्रति क्विंटल",
    "farmer.successRate": "सफलता दर",
    "farmer.transactions": "लेनदेन",
    "farmer.yieldPerformance": "फसल प्रदर्शन",
    "farmer.yourYieldVsAverage": "आपकी फसलें बनाम क्षेत्र औसत",
    "farmer.quickActions": "त्वरित कार्य",
    "farmer.predictCrop": "फसल पूर्वानुमान",
    "farmer.pricePredictions": "मूल्य पूर्वानुमान",
    "farmer.findTraders": "व्यापारी खोजें",
    "farmer.addMyCrop": "मेरी फसल जोड़ें",
    "farmer.needHelp": "मदद चाहिए?",
    "farmer.support": "समर्थन",
    "farmer.myCrops": "मेरी सक्रिय फसलें",
    "farmer.myCropsDescription": "अपनी सूचीबद्ध सभी फसलों को देखें और प्रबंधित करें",
    "farmer.noCrops": "आपने अभी तक कोई फसल नहीं जोड़ी है",
    "farmer.traderRequestsDescription": "अपनी फसलों में रुचि रखने वाले व्यापारियों से अनुरोध प्रबंधित करें",
    "farmer.noTraderRequests": "फिलहाल कोई व्यापारी अनुरोध नहीं है",
    // Farmer Add Crop
    "addCrop.title": "बिक्री के लिए अपनी फसल जोड़ें",
    "addCrop.subtitle": "व्यापारियों से जुड़ने के लिए अपनी फसल का विवरण सूचीबद्ध करें",
    "addCrop.cropName": "फसल का नाम",
    "addCrop.cropNamePlaceholder": "उदा., गेहूं, चावल, कपास",
    "addCrop.quantity": "मात्रा (किलो में)",
    "addCrop.quantityPlaceholder": "उदा., 5000",
    "addCrop.pricePerKg": "प्रति किलो मूल्य (₹)",
    "addCrop.pricePlaceholder": "उदा., 25",
    "addCrop.location": "स्थान",
    "addCrop.locationPlaceholder": "उदा., पंजाब",
    "addCrop.description": "विवरण",
    "addCrop.descriptionPlaceholder": "गुणवत्ता, कटाई की तारीख, आदि",
    "addCrop.phone": "संपर्क फोन",
    "addCrop.phonePlaceholder": "+91 98765 43210",
    "addCrop.success": "फसल सफलतापूर्वक सूचीबद्ध की गई!",
    // Dhalari Dashboard
    "dhalari.welcome": "स्वागत है, व्यापारी!",
    "dhalari.subtitle": "किसान अनुरोधों को प्रबंधित करें, आय को ट्रैक करें और अपने व्यवसाय को बढ़ाएं",
    "dhalari.pendingRequests": "उपलब्ध फसलें",
    "dhalari.acceptedDeals": "स्वीकृत सौदे",
    "dhalari.totalEarnings": "कुल खर्च",
    "dhalari.thisMonth": "इस महीने",
    "dhalari.avgDealValue": "औसत डील मूल्य",
    "dhalari.perTransaction": "स्थिति के अनुसार",
    "dhalari.weeklyEarnings": "साप्ताहिक खर्च",
    "dhalari.yourEarningsThisWeek": "इस सप्ताह आपका खर्च",
    "dhalari.viewRequests": "फसलें देखें",
    "dhalari.myProfile": "मेरी प्रोफाइल",
    "dhalari.analytics": "विश्लेषण",
    "dhalari.profileStats": "प्रोफाइल आंकड़े",
    "dhalari.rating": "रेटिंग",
    "dhalari.successRate": "सफलता दर",
    "dhalari.verified": "सत्यापित",
    // Dhalari Requests
    "requests.title": "किसान फसल सूची",
    "requests.subtitle": "किसानों से उपलब्ध फसलों को ब्राउज़ करें",
    "requests.farmerName": "किसान का नाम",
    "requests.crop": "फसल",
    "requests.quantity": "मात्रा",
    "requests.price": "मूल्य",
    "requests.location": "स्थान",
    "requests.phone": "फोन",
    "requests.accept": "सौदा स्वीकार करें",
    "requests.contact": "किसान से संपर्क करें",
    // Find Verified Traders
    find_verified_traders: "सत्यापित व्यापारी खोजें",
    connect_with_trusted_dhalaris: "अपने क्षेत्र में विश्वसनीय दलालों (कृषि व्यापारियों) से जुड़ें",
    filter_by_crop: "फसल के अनुसार फ़िल्टर करें",
    filter_by_location: "स्थान के अनुसार फ़िल्टर करें",
    all_crops: "सभी फसलें",
    wheat: "गेहूं",
    rice: "चावल",
    cotton: "कपास",
    sugarcane: "गन्ना",
    all_locations: "सभी स्थान",
    punjab: "पंजाब",
    haryana: "हरियाणा",
    maharashtra: "महाराष्ट्र",
    delhi: "दिल्ली",
    west_bengal: "पश्चिम बंगाल",
    specializations: "विशेषज्ञता",
    experience: "अनुभव",
    years: "वर्ष",
    commission_rate: "कमीशन दर",
    contacting: "संपर्क कर रहे हैं",
    no_traders_found: "चयनित फ़िल्टर के साथ कोई व्यापारी नहीं मिला। अपनी खोज को समायोजित करने का प्रयास करें।",
    "dashboard.availableCrops": "उपलब्ध फसलें",
    "dashboard.clickBrowse": "मार्केटप्लेस ब्राउज़ करने के लिए क्लिक करें",
    "dashboard.view": "देखें",
    "dashboard.activePartnerships": "सक्रिय साझेदारी",
    "dashboard.commissionEarned": "स्वीकृत फसलों पर",
    "dashboard.currentlyListed": "वर्तमान में सूचीबद्ध",
    "dashboard.cropRequests": "फसल अनुरोध",
    "dashboard.fromDealers": "आपकी फसलों के लिए डीलरों से",
    "dashboard.contactRequests": "संपर्क अनुरोध",
    "dashboard.connectionRequests": "कनेक्शन अनुरोध",
    "dashboard.signIn": "साइन इन",
    "dashboard.goHome": "होम पर जाएं",
    "dashboard.signInGoogle": "Google से साइन इन करें",
    "dashboard.pleaseSignIn": "अपने डैशबोर्ड तक पहुंचने के लिए कृपया साइन इन करें",
    "dashboard.farmerDashboard": "किसान डैशबोर्ड",
    "dashboard.dhalariDashboard": "ढालरी डैशबोर्ड",
    "stats.performanceStatistics": "📊 प्रदर्शन सांख्यिकी",
    "stats.dealSuccessRate": "डील सफलता दर",
    "stats.excellent": "उत्कृष्ट",
    "stats.good": "अच्छा",
    "stats.needsImprovement": "सुधार आवश्यक",
    "stats.starting": "शुरुआत",
    "stats.acceptedOutOf": "स्वीकृत में से",
    "stats.totalRequests": "कुल अनुरोध",
    "stats.basedOnDeals": "स्वीकृत डील्स के आधार पर",
    "stats.revenueBreakdown": "राजस्व विवरण",
    "stats.totalTradeValue": "कुल व्यापार मूल्य",
    "stats.yourCommission": "आपका कमीशन (10%)",
    "stats.avgPerDeal": "प्रति डील औसत",
    "stats.todaysMarket": "आज की बाजार स्थिति",
    "stats.marketTrend": "बाजार रुझान",
    "stats.activeFarmers": "सक्रिय किसान",
    "stats.newListingsToday": "आज की नई सूची",
    "stats.topCrop": "शीर्ष फसल",
    "stats.totalListings": "कुल सूची",
    "stats.monthlyPerformance": "📈 मासिक प्रदर्शन सारांश",
    "stats.tradingPerformance": "हाल के महीनों में आपका व्यापार प्रदर्शन",
    "stats.deals": "डील्स",
    "stats.requestSummary": "अनुरोध सारांश",
    "stats.cropDeals": "फसल डील्स",
    "stats.total": "कुल",
    "stats.yourStatus": "आपकी स्थिति",
    "stats.activeCrops": "सक्रिय फसलें",
    "stats.avgPriceQuintal": "प्रति क्विंटल औसत मूल्य",
    "stats.profileStatus": "प्रोफ़ाइल स्थिति",
    "stats.active": "सक्रिय",
    "stats.monthlyPerformanceChart": "मासिक प्रदर्शन",
    "stats.chartDescription": "फसलें, अनुरोध, बिक्री और राजस्व",
    "actions.manageTrading": "अपनी व्यापारिक गतिविधियाँ प्रबंधित करें",
    "actions.manageActivities": "अपनी गतिविधियाँ प्रबंधित करें",
    "actions.contactRequests": "संपर्क अनुरोध",
    "actions.browseMarketplace": "मार्केटप्लेस ब्राउज़ करें",
    "actions.connectionsChat": "💬 कनेक्शन और चैट",
    "actions.findFarmers": "किसान खोजें",
    "support.querySupport": "प्रश्न सहायता और मदद",
    "support.needAssistance": "सहायता चाहिए? प्लेटफ़ॉर्म सुविधाओं के साथ मदद प्राप्त करें और अपने प्रश्नों का समाधान करें",
    "support.commonTopics": "सामान्य विषय:",
    "support.paymentDisputes": "भुगतान विवाद और लेनदेन समस्याएं",
    "support.profileVerification": "प्रोफ़ाइल सत्यापन सहायता",
    "support.marketplaceGuidelines": "मार्केटप्लेस सूची दिशानिर्देश",
    "support.openSupportCenter": "सहायता केंद्र खोलें",
    "support.queryAndSupport": "प्रश्न और सहायता",
    "support.getHelp": "अपने प्रश्नों के लिए सहायता प्राप्त करें या समस्याएं रिपोर्ट करें",
    "support.submitQuery": "प्रश्न सबमिट करें",
    "support.fillForm": "नीचे दिया गया फ़ॉर्म भरें और हम जल्द ही आपसे संपर्क करेंगे",
    "support.queryCategory": "प्रश्न श्रेणी *",
    "support.selectCategory": "श्रेणी चुनें",
    "support.technicalIssue": "तकनीकी समस्या",
    "support.paymentRelated": "भुगतान संबंधित",
    "support.cropInformation": "फसल जानकारी",
    "support.farmerContact": "किसान संपर्क",
    "support.other": "अन्य",
    "support.subject": "विषय *",
    "support.subjectPlaceholder": "अपनी समस्या का संक्षिप्त विवरण",
    "support.description": "विवरण *",
    "support.descriptionPlaceholder": "अपने प्रश्न का विस्तार से वर्णन करें...",
    "support.submitting": "सबमिट हो रहा है...",
    "support.submitQueryBtn": "प्रश्न सबमिट करें",
    "support.contactSupport": "सहायता से संपर्क करें",
    "support.phoneSupport": "फ़ोन सहायता",
    "support.emailSupport": "ईमेल सहायता",
    "support.platformInstructions": "प्लेटफ़ॉर्म निर्देश",
    "support.quickGuide": "व्यापारी के रूप में AgriConnect उपयोग करने की त्वरित गाइड",
    "support.browseAvailCrops": "1. उपलब्ध फसलें ब्राउज़ करें",
    "support.browseAvailCropsDesc": "किसानों से मात्रा, मूल्य और स्थान जैसे विवरणों के साथ फसल सूचियाँ देखने के लिए \"अनुरोध देखें\" पर जाएं।",
    "support.acceptDeals": "2. डील स्वीकार करें",
    "support.acceptDealsDesc": "डील को अंतिम रूप देने के लिए किसी भी सूची पर \"स्वीकार करें\" क्लिक करें। आप कुल मूल्य पर 5% कमीशन कमाएंगे।",
    "support.sendCropRequests": "3. फसल अनुरोध भेजें",
    "support.sendCropRequestsDesc": "किसानों को बताने के लिए \"फसल अनुरोध भेजें\" का उपयोग करें कि आप कौन सी फसलें खोज रहे हैं। किसानों को सूचना मिलेगी।",
    "support.trackEarnings": "4. कमाई ट्रैक करें",
    "support.trackEarningsDesc": "डैशबोर्ड और एनालिटिक्स अनुभागों में अपनी एनालिटिक्स और कमाई विवरण देखें।",
    "support.faq": "अक्सर पूछे जाने वाले प्रश्न",
    "support.faq1q": "किसानों से कैसे संपर्क करें?",
    "support.faq1a": "प्रत्येक फसल सूची में किसान का फ़ोन नंबर दिखाई देता है। डील विवरण पर चर्चा के लिए आप उन्हें सीधे कॉल या WhatsApp कर सकते हैं।",
    "support.faq2q": "कमीशन दर क्या है?",
    "support.faq2a": "आप स्वीकार की गई हर डील पर 5% कमीशन कमाते हैं। उदाहरण के लिए, ₹1,00,000 की डील पर, आप ₹5,000 कमाते हैं।",
    "support.faq3q": "मुझे भुगतान कैसे मिलता है?",
    "support.faq3a": "कमाई स्वचालित रूप से ट्रैक की जाती है। हर महीने के अंत में डायरेक्ट ट्रांसफ़र प्राप्त करने के लिए अपनी प्रोफ़ाइल में बैंक विवरण सेट करें।",
    "support.faq4q": "क्या स्वीकार करने के बाद डील अस्वीकार कर सकते हैं?",
    "support.faq4a": "स्वीकार करने के बाद, डील्स अंतिम हो जाती हैं। असाधारण परिस्थितियों के कारण रद्द करने की आवश्यकता हो तो कृपया तुरंत सहायता से संपर्क करें।",
    "support.faq5q": "अपनी प्रोफ़ाइल कैसे अपडेट करें?",
    "support.faq5a": "अपनी व्यावसायिक जानकारी, फसल विशेषज्ञता और संपर्क विवरण संपादित करने के लिए त्वरित कार्यों अनुभाग में \"मेरी प्रोफ़ाइल\" पर जाएं।",
    "support.querySubmitted": "आपका प्रश्न सबमिट हो गया है। हम 24 घंटे के भीतर जवाब देंगे।",
    "support.fillAllFields": "कृपया सभी फ़ील्ड भरें",
    "support.failedSubmit": "प्रश्न सबमिट करने में विफल",
    "market.cropMarketplace": "फसल मार्केटप्लेस",
    "market.browseDescription": "किसानों से उपलब्ध फसलें ब्राउज़ करें और सीधे ऑफ़र करें।",
    "market.searchPlaceholder": "फसलें, किसान या स्थान खोजें...",
    "market.loadingData": "बाजार डेटा लोड हो रहा है...",
    "market.noCrops": "बाजार में वर्तमान में कोई फसल उपलब्ध नहीं है।",
    "market.requestDeal": "डील अनुरोध",
    "market.makeOffer": "ऑफ़र दें",
    "market.sendPurchase": "खरीद अनुरोध भेजें",
    "market.quantity": "मात्रा (किलो)",
    "market.available": "उपलब्ध:",
    "market.offerPrice": "ऑफ़र मूल्य (₹/किलो)",
    "market.expected": "अपेक्षित:",
    "market.messageOptional": "संदेश (वैकल्पिक)",
    "market.messagePlaceholder": "डिलीवरी विवरण या बातचीत नोट्स जोड़ें...",
    "market.sending": "भेज रहे हैं...",
    "market.sendRequest": "अनुरोध भेजें",
    "market.requestSent": "अनुरोध भेजा गया!",
    "market.locationNotSpecified": "स्थान निर्दिष्ट नहीं",
    "market.hiddenConnect": "छिपा (कनेक्ट)",
    "market.connected": "कनेक्टेड",
    "market.back": "वापस",
    "chat.connectionsAndChat": "कनेक्शन और चैट",
    "chat.connected": "कनेक्टेड",
    "chat.connections": "कनेक्शन",
    "chat.requests": "अनुरोध",
    "chat.searchConnections": "कनेक्शन खोजें...",
    "chat.noConnections": "अभी तक कोई कनेक्शन नहीं",
    "chat.findTradersHint": "व्यापारी खोजें और कनेक्ट होने के लिए अनुरोध भेजें",
    "chat.findFarmersHint": "किसान खोजें और कनेक्ट होने के लिए अनुरोध भेजें",
    "chat.startChatting": "कनेक्टेड — चैट शुरू करें!",
    "chat.noPendingRequests": "कोई लंबित अनुरोध नहीं",
    "chat.yourMessages": "आपके संदेश",
    "chat.selectConnection": "चैट शुरू करने के लिए एक कनेक्शन चुनें",
    "chat.connectedOn": "कनेक्ट हुए",
    "chat.sayHello": "👋 नमस्ते कहें! बातचीत शुरू करें।",
    "chat.typeMessage": "संदेश टाइप करें...",
    "chat.accessDenied": "पहुँच अस्वीकृत",
    "chat.signInFarmer": "कृपया किसान के रूप में साइन इन करें।",
    "chat.signInDealer": "कृपया डीलर के रूप में साइन इन करें।",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    // Load saved language from localStorage on mount
    const savedLanguage = localStorage.getItem("app-language") as Language
    if (savedLanguage && ["en", "te", "hi"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
    setMounted(true)
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("app-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  if (!mounted) return null

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
